# TODO: Try and put this in .config
# TODO: Fix this
license_id: "hdx-other"
license_other: >
  Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Intergovernmental
  Organization (CC BY-NC-SA 3.0 IGO). Click
  [here](https://www.who.int/about/policies/publishing/copyright)
  for more information.
caveats: "More details about the indicators are available in the links in the dataset description."
methodology: "Registry"
dataset_source: "Climate Emergency Software Alliance"
package_creator: "HDX Data Systems Team"
private: False  # has to be True or False
